// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"p56r3ggc13","name":"LambdaMicroservice","description":"Created by AWS Lambda","endpoint":"https://p56r3ggc13.execute-api.us-east-1.amazonaws.com/prod","region":"us-east-1","paths":["/Dan_Test"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:c2e41e16-1782-46cf-80a9-c7ad7a1d7ecf',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'knowladgemanagermobi-hosting-mobilehub-1544758271',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3q1iea3axadj9.cloudfront.net',
    'aws_mobile_analytics_app_id': '68c2eb21783b47b28d37ad748802544a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1b8a8dab-0c41-4516-9272-74a14e44195e',
    'aws_project_name': 'KnowladgeManagerMobile',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'knowladgemanagermobi-mobilehub-1544758271',
}

export default awsmobile;
